#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#validate the commit message
pnpm commitlint --edit $1

#validate the files that have changed using eslint
pnpm eslint 

#validate the files that have changed using eslint
pnpm eslint 
